### ISSUE TITLE
GPT4 model not woking

### ISSUE THREAD

**Issue by elkwaet** [marcolardera/chatgpt-cli#13]
There is what i get when change the model in the config yaml file:

`godoevix ~ > chatgpt
ChatGPT CLI
Model in use: gpt-4

[0] >>> So ?
Unknown error, status code 404
{
    'error': {
        'message': 'The model: `gpt-4` does not exist',
        'type': 'invalid_request_error',
        'param': None,
        'code': 'model_not_found'
    }
}

Total tokens used: 0
Estimated expense: $0.0
`

**Comment by marcolardera** [comment]
GPT-4 APIs are in beta and limited only to some users.

The error message you got means that your OpenAI account don't have access to the gpt-4 model (yes, I know they could have used a more precise error message...). In order to gain access you need to join the waitlist: https://openai.com/waitlist/gpt-4-api

**Comment by marcolardera** [comment]
Anyway, the feedback about the error message has already been given to OpenAI: https://community.openai.com/t/better-error-message-when-the-account-doesn-t-have-access-to-a-model/102905
