### ISSUE TITLE
Lost history / context

### ISSUE THREAD

**Issue by ashpoolin** [marcolardera/chatgpt-cli#21]
This tool is wonderful, btw. Thanks for building it!

I had a great series of prompts going and then I sent one more, and the program failed after returning the following fault:
```
Maximum context length exceeded
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/<username>/Documents/chatgpt-cli/chatgpt.py", line 79, in display_expense
    PRICING_RATE[model]["prompt"],
KeyError: 'gpt-3.5-turbo-0301'
```

Unfortunately, it lost the context that had accumulated. In general, is there a way for the API to remember sessions used in chatgpt-cli, or is the API essentially an atomic session (a "chat"?) that is gone after the program ends?

Again, thanks for what you do!
ASH

**Comment by marcolardera** [comment]
Hello,

thank you for the feedback!

gpt-3.5-turbo has a token limit of 4096. If you exceed this value it will throw an error. This limit is calculated as context token + user token + response token, there is no way around. 

ChatGPT has no memory of previous messages in itself: that's why, in order to have a conversation, we need to send the full message history (including the context if any) at each API call. When the script is closed it loses this data. Maybe I can implement a save/restore functionality that saves the conversation on the client machine, but the token limit still applies, so you will not be able to continue a conversation forever.

Note that gpt-4 have higher token limits: https://platform.openai.com/docs/models/gpt-4

**Comment by ashpoolin** [comment]
Ahh this issue just a lack of me understanding how the token limit works. I'll get on that. Thanks for the reply!
